README.md
main.go
vulns.go
vulns_test.go

Adding more filtering capabilities for new Snyk capabilities.
-priorityScoreThreshold=[0-1000]                                    
// Optional. Your min priority score threshold
-maturityFilter=[mature,proof-of-concept,no-known-exploit,no-data] 
// Optional. include only maturity level(s). Separated by commas

feat: Add maturity levels filters and min priorityScore threshold

---

snyk_utils.go

Adding user agent in the requests

minor: add user agent to requests

---

snyk_utils.go

change user agent field in request header.

fix: change user agent

---

.circleci/config.yml

go is not pre installed in gcr.io/snyk-technical-services/cicd-github so need to add a line for it

chore: change release process

---

.circleci/config.yml

I am resetting this, until I figure out why the gorelease flow is failing (I was using a different docker image on my test project)

minor: resetting release process

---

.circleci/config.yml
fixtures/snyk_code_fixtures/snykCodeDataHighIssuesWithPagination.json
fixtures/snyk_code_fixtures/snykCodeIssueDetailsForPagination.json
fixtures/yamlFileForMandatoryFieldTestWithSpecialField/jira.yaml
jira_snyk_code_test.go
utils_test.go
vulns.go

Fix pagination for snyk code issues.
If next is present get the url send new requests with that url

fix: fix pagination for v3 api

---

.github/CODEOWNERS
.github/PULL_REQUEST_TEMPLATE.md

Adding the codeowners file and the PR template

minor: add GH folder with coderowners and template files

---

README.md

This repo is maintenance only mode

docs: mark as in maintenance mode

---

README.md

Document each option with more details & links to Snyk + Jira docs.

chore: enhanced options information

---

fixtures/jira.yaml
fixtures/yamlFileForMandatoryFieldTest/jira.yaml
fixtures/yamlFileForMandatoryFieldTestWithSpecialField/jira.yaml
fixtures/yamlFileWithNestedMandatoryFieldTest/jira.yaml
utils_test_test.go

Correct orgId Example to use uuid

minor: correct orgID example to use uuid

---

README.md

Add the new way to install package in go
_Instructions on how to run this locally, background context, what to review, questions…_
- [Link to documentation](https://github.com/snyk-tech-services/jira-tickets-for-new-vulns/wiki/)
_Visuals that may help the reviewer_

minor: add alternative way to install

---

README.md

Fix readme entry for the new supported format.
_Instructions on how to run this locally, background context, what to review, questions…_
- [Link to documentation](https://github.com/snyk-tech-services/jira-tickets-for-new-vulns/wiki/)
_Visuals that may help the reviewer_

minor: fix the readme

---

fixtures/snyk_code_fixtures/snykCodeDataHighIssuesIgnored.json
fixtures/snyk_code_fixtures/snykCodeIssueDetailsWithIgnore.json
jira_snyk_code_test.go
utils_test.go
vulns.go

Adding a test on the ignored field of the code issue and skipping if true => issue is not added to the list of code issues to create.
_Instructions on how to run this locally, background context, what to review, questions…_
- [Link to documentation](https://github.com/snyk-tech-services/jira-tickets-for-new-vulns/wiki/)
- linked to zendesk ticket https://snyk.zendesk.com/agent/tickets/31745
- https://snyksec.atlassian.net/browse/TECHSERV-3340
_Visuals that may help the reviewer_

minor: add a check on the ignore field of code issues to filter them out

---

fixtures/jira.yaml
fixtures/yamlFileForCustomMandatoryFieldTest/jira.yaml
fixtures/yamlFileForMandatoryFieldTest/jira.yaml
fixtures/yamlFileForMandatoryFieldTestWithSpecialField/jira.yaml
fixtures/yamlFileWithNestedMandatoryFieldTest/jira.yaml
jira_test.go
jira_utils.go
main.go
snyk.go
utils.go
utils_test_test.go
vulns.go
vulns_test.go

- [ x] Tests written and linted [ℹ︎](https://github.com/snyk/general/wiki/Tests)
Checking the config file format early.
Checking that only the snyk and jira options supported are specified and that the custom field follows the expected format.
- [TECHSERV-3221](https://snyksec.atlassian.net/jira/software/c/projects/TECHSERV/boards/387?modal=detail&selectedIssue=TECHSERV-3221)
_Visuals that may help the reviewer_

minor: check the config file format early

---

README.md

docs: mark as inactively maintained

---

README.md

Update docs to explain the config path is to the directory

patch: update docs on config file path

---

fixtures/org.json
snyk.go

Filter out projects that are not monitored
https://github.com/snyk-tech-services/jira-tickets-for-new-vulns/issues/163

minor: filter out projects that are not monitored

---

.gitignore
snyk.go

Fix project listing as it got broken in release https://github.com/snyk-tech-services/jira-tickets-for-new-vulns/releases/tag/3.36.1

major: fix project listing

---

README.md
fixtures/snyk_code_fixtures/snykCodeData.json
fixtures/snyk_code_fixtures/snykCodeDataHighIssues.json
fixtures/snyk_code_fixtures/snykCodeDataHighIssuesIgnored.json
fixtures/snyk_code_fixtures/snykCodeDataLowIssues.json
fixtures/snyk_code_fixtures/snykCodeDataMediumIssues.json
jira.go
utils_test.go
vulns.go

Ensure priority threshold filter is respected for SnykCode issues too by upgrading the API version used and filtering manually

minor: filter out Code Issues based on priorityScore if set

---

README.md
fixtures/jira.yaml
fixtures/yamlFileForCustomMandatoryFieldTest/jira.yaml
fixtures/yamlFileForMandatoryFieldTest/jira.yaml
utils.go

Fixes tests and add readme note about breaking change.

major: release fixes+improvements with assigneeId breaking change

---

vulns.go

fix: allow for custom api hostname for regional instance

---

README.md
vulns.go

Releases fix for custom api endpoint for Snyk Regional instances.

release fix

---

README.md

Force triggers a release.
Removing the develop branch stop and merging directly PRs into master.

patch: force release

---

README.md

fix: force trigger release

---

LICENSE

Triggers release to include targetId option.

minor: trigger release
